### ISSUE TITLE
Move timestamp to the top level of the JSON object of metadata endpoint

### ISSUE THREAD

**Issue by bdickason** [srstafford1996/chicken-server#9]
Endpoint: http://bdickason.com:3001/api/metadata

Change request: Any time a character is updated, the last_updated field for the entire object should be changed (rather than on a per-character basis)

From @ndejesus1227
So I checked the meta data and see the last_updated value is inside the data for each character
I was hoping to see it on the highest level
Like, if any character at all got updated it would update the last_updated value regardless of who it was specifically
maybe later on we can do something where it only checks who got updated
but for right now, ya know?

**Comment by dayhaysoos** [comment]
I actually gave @srstafford1996  that feedback in the facebook chat! Word for word haha. It'll get taken care of :)

**Comment by bdickason** [comment]
@ndejesus1227 I just copy/pasted what you said here so we could keep track of it :P

**Comment by bdickason** [comment]
@srstafford1996 Ugly solution, but it works. Basic happy path test coverage included
